all:
	pdflatex lab.tex
	pdflatex lab.tex
	pdflatex lab.tex
	latex questions.tex
	latex questions.tex
	latex questions.tex
	dvipdf questions
clean:
	rm -f *.aux *.bbl *.blg *.dvi *.glo *.ist *.log *.pdf
